### ISSUE TITLE
Is there a workaround to run /init with non-zero PID?

### ISSUE THREAD

**Issue by dicearr** [just-containers/s6-overlay#383]
In version 2.x I was able to run `/init` with a non-zero PID. However, after updating to v3 I've realized that this is no longer possible.

Although I'm pretty sure this is a conscious and well-reasoned decision, I am using a cloud provider that does not allow me to replace their PID 1 process. So my question is; Is there a workaround I can use for running v3 without PID 1? And if that is the case, what would I be losing by not running S6 as PID 1?

**Comment by skarnet** [comment]
s6-overlay is meant to run in containers, which means, among other things, a pid namespace, in which you can run your own pid 1.
If your cloud provider does not implement pid namespaces, it does not provide you with containers - and then s6-overlay is not the tool you need.
You can use [s6](https://skarnet.org/software/s6/index.html) to run your services on your cloud system, without wrapping it in s6-overlay.

Or am I misunderstanding your situation?

**Comment by dicearr** [comment]
Thank for the quick response @skarnet. The cloud provider (Heroku) supports containers, and I am in fact using my own Dockerfile. However, although I have a single ENTRYPOINT and no CMD command, the PID 1 is taken by a process called `ps-run` which I suspect is from their side. I've nonetheless also opened a ticket in Heroku to see if I am misconfiguring something. 

PD: The same Dockerfile running locally results in the `/init` process running with PID 1.

**Comment by skarnet** [comment]
Yeah, their Docker setup sounds shifty - I'd be interested in knowing what they answer to your ticket. It may be that they provide their own init system to the container - in which case, if it's not possible to disable it, you unfortunately won't be able to run s6-overlay there - but you can still run s6 under their own init system.

**Comment by dicearr** [comment]
Sure, I will post their reply here if I think it is helpful in any way. From my side this issue can be closed. Thanks for your time.

**Comment by skarnet** [comment]
Closing the issue then, but I'll definitely read the answer, because `ps-run` is... unusual. 😄

**Comment by dicearr** [comment]
After some conversations with Heroku support this is the most interesting bit:

> I've done some digging and found that ps-run will always be given PID 1 as it's necessary to facilitate our hosting and communication. As you suspected in your original comment you'll be unable to obtain PID 1 for your /init and will have to create a workaround.

And the final conclusion:

> In short, this won't be possible to implement that way in Heroku. You will not be able to take PID 1 away from ps-run, and you also will not be able to obtain root on your dynos, which I believe would be required for 're-parenting processes'. I hate to be the bearer of bad news - but based upon the description of your implementation - the team and myself find it unlikely to work with Heroku if PID 1 is a requirement.

So if you see in the future any issue about `/init` not running with PID 1, Heroku might be involved.

**Comment by skarnet** [comment]
I'm sorry to hear that. It sounds like dynos are not containers - they may *run* in containers, but if they don't give you full control of the container, and instead provide you with a pid 1 and a normal user (not even the root user) to run processes as, then you don't get a container, you get a process hierarchy with restricted functionality.

And of course, nobody is going to hold Heroku accountable for lying to their users. 🤷

**Comment by RangelReale** [comment]
I had the same problem in AWS Lambda with extensions, the extensions run before the entrypoint, so PID 1 was already taken.
